# https://js.langchain.com/docs/integrations/vectorstores/pgvector/
services:
  db:
    hostname: 127.0.0.1
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypwd
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql